### Part 1. Retrieve and save token.
POST http://localhost/auth/token/login
Content-Type: application/x-www-form-urlencoded

grant_type=&username=admin%40example.com&password=password&scope=&client_id=&client_secret=

> {%
    client.global.set("auth_token", response.body.access_token);
%}

### Part 2. Root.
GET http://localhost
Authorization: Bearer {{auth_token}}
Content-Type: application/json
