# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protos import email_pb2 as email__pb2


class EmailServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendEmail = channel.stream_unary(
                '/pkg.email.EmailService/SendEmail',
                request_serializer=email__pb2.EmailRequest.SerializeToString,
                response_deserializer=email__pb2.EmailResponse.FromString,
                )


class EmailServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendEmail(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EmailServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendEmail': grpc.stream_unary_rpc_method_handler(
                    servicer.SendEmail,
                    request_deserializer=email__pb2.EmailRequest.FromString,
                    response_serializer=email__pb2.EmailResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pkg.email.EmailService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class EmailService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendEmail(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/pkg.email.EmailService/SendEmail',
            email__pb2.EmailRequest.SerializeToString,
            email__pb2.EmailResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
