# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: email.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x65mail.proto\x12\tpkg.email\"r\n\x0c\x45mailRequest\x12*\n\nemail_info\x18\x01 \x01(\x0b\x32\x14.pkg.email.EmailInfoH\x00\x12+\n\nattachment\x18\x02 \x01(\x0b\x32\x15.pkg.email.AttachmentH\x00\x42\t\n\x07payload\"h\n\tEmailInfo\x12\x14\n\x0c\x66rom_address\x18\x01 \x01(\t\x12\x12\n\nto_address\x18\x02 \x01(\t\x12\x0f\n\x07subject\x18\x03 \x01(\t\x12\x12\n\nplain_text\x18\x04 \x01(\t\x12\x0c\n\x04html\x18\x05 \x01(\t\"B\n\nAttachment\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x12\x14\n\x0c\x63ontent_type\x18\x03 \x01(\t\"1\n\rEmailResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2P\n\x0c\x45mailService\x12@\n\tSendEmail\x12\x17.pkg.email.EmailRequest\x1a\x18.pkg.email.EmailResponse(\x01\x42\x31Z/github.com/accentdesign/grpc/services/email/pkgb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'email_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z/github.com/accentdesign/grpc/services/email/pkg'
  _EMAILREQUEST._serialized_start=26
  _EMAILREQUEST._serialized_end=140
  _EMAILINFO._serialized_start=142
  _EMAILINFO._serialized_end=246
  _ATTACHMENT._serialized_start=248
  _ATTACHMENT._serialized_end=314
  _EMAILRESPONSE._serialized_start=316
  _EMAILRESPONSE._serialized_end=365
  _EMAILSERVICE._serialized_start=367
  _EMAILSERVICE._serialized_end=447
# @@protoc_insertion_point(module_scope)
